[project]
name = "agent-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langfuse<3.0.0",
    "litellm>=1.78.0",
    "openai>=2.3.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.50.0",
]
